version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "aws-cdk"
      - dependency-name: "@aws-cdk/*"
    assignees:
      - "bmacher"
